#!/usr/local/bin/bash

export PGPASSWORD="76BIUysT"
BACKUP_HOST="pg199"
BACKUP_USER="postgres2"
BACKUP_PATH="~/backups"
RETENTION_DAYS=28

BACKUP_NAME="pg_full_$(date +%Y%m%d_%H%M%S).sql.gz"
TEMP_BACKUP="/tmp/$BACKUP_NAME"

pg_dump -p 9746 -U testuser -d loudwhiteuser -F p | gzip > "$TEMP_BACKUP"

scp "$TEMP_BACKUP" "$BACKUP_USER@$BACKUP_HOST:$BACKUP_PATH/"

rm -f "$TEMP_BACKUP"

unset PGPASSWORD

ssh "$BACKUP_USER@$BACKUP_HOST" "find $BACKUP_PATH -name 'pg_full_*.sql.gz' -mtime +$RETENTION_DAYS -delete"
