CREATE TABLESPACE kls10 LOCATION '/var/db/postgres2/kls10';
CREATE TABLESPACE opy85 LOCATION '/var/db/postgres2/opy85';
CREATE ROLE testuser WITH LOGIN PASSWORD 'testpass';
GRANT CONNECT ON DATABASE template1 TO testuser;
CREATE DATABASE loudwhiteuser OWNER testuser TEMPLATE template1 ENCODING 'KOI8-R' LC_COLLATE 'ru_RU.KOI8-R' LC_CTYPE 'ru_RU.KOI8-R';
GRANT CREATE ON TABLESPACE kls10 TO testuser;
GRANT CREATE ON TABLESPACE opy85 TO testuser;